### ISSUE TITLE
Update Plugin for Plugin Manager 2.0

### ISSUE THREAD

**Issue by plafosse** [Alex3434/Binja-SigMaker#1]
With the introduction of the Binary Ninja Plugin Manager 2.0 we will be releasing a installation UI for all plugins in the community repository. Please check https://binary.ninja/2019/07/04/plugin-manager-2.0.html for the latest information about how to submit your plugin. If you no longer want your plugin in the repository please disregard this issue

**Comment by psifertex** [comment]
FYI, due to the lack of response on updating this plugin, I'm replacing it with the more recent fork here: https://github.com/apekros/binja_sigmaker

**Comment by Alex3434** [comment]
Yeah, the fork is probably the right choice as for now. 
Thanks to [aprekros](https://github.com/apekros) for the update!
